### PR TITLE
Master

### PR DESCRIPTION
**Pull request by dkorolev**

### CODE REVIEW

**Comment by dkorolev** [comment]
CC @mzhurovich

**Comment by sompylasar** [comment]
@dkorolev The Bash scripts should be updated from https://github.com/KnowSheet/Bricks/pull/104 .

**Comment by dkorolev** [comment]
@sompylasar Thanks for the pointer, updated `KnowSheet/Scripts`.

**Comment by dkorolev** [comment]
Closing, continuing in https://github.com/KnowSheet/fncas/pull/3.

**Pull request closed without merging**
